name: flutter_messenger
description: "Messenger application thats been written to do the technical assignment from Mozz"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.2

dependency_overrides:
  web: ^0.5.1
  firebase_auth_web: ^5.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

